[package]
name = "grep_caselaw"
version = "0.1.0"
authors = ["Jack Cushman <jcushman@law.harvard.edu>"]

[dependencies]
regex = "1"
glob = "0.2"
rayon = "1.0"
redis = "0.8.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = "2.32.0"